#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
name = "my-notes-api"

# Workers Logs
[observability]
enabled = true

# Bind a D1 database
[[d1_databases]]
binding = "DB"
