#:schema node_modules/wrangler/config-schema.json
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
name = "my-notes-api"

# Workers Logs
[observability]
enabled = true

# Bind a D1 database
[[d1_databases]]
binding = "DB"
database_id = "4ae27f92-0b43-4671-b9fd-6c86cfea64ca"
database_name = "my-notes"
migrations_dir = "drizzle/migrations"
